workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Create iOS project structure
        script: |
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            echo "iOS project not found, creating..."
            flutter create --platforms=ios --org com.emanneul --project-name knot .
          else
            echo "iOS project already exists"
          fi
          # Ensure Podfile exists
          if [ ! -f "ios/Podfile" ]; then
            echo "Creating Podfile..."
            cd ios
            pod init
            cd ..
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - emm049@bucknell.edu
        notify:
          success: true
          failure: true
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: $IOS_APP_ID
          groups:
            - beta-testers
