workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Create iOS project structure
        script: |
          echo "Checking iOS project structure..."
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            echo "iOS project not found, creating..."
            # Remove ios folder if it exists but is incomplete
            if [ -d "ios" ]; then
              echo "Removing incomplete ios folder..."
              rm -rf ios
            fi
            # Create iOS project with correct org and name
            flutter create --platforms=ios --org com.emanneul --project-name knot .
            echo "iOS project created"
          else
            echo "iOS project already exists"
          fi
          # Verify xcodeproj exists
          if [ ! -d "ios/Runner.xcodeproj" ]; then
            echo "ERROR: xcodeproj still not found after creation!"
            ls -la ios/
            exit 1
          fi
          echo "iOS project structure verified"
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - emm049@bucknell.edu
        notify:
          success: true
          failure: true
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: $IOS_APP_ID
          groups:
            - beta-testers
